#Get all posts
GET http://localhost:9080/simple-rpg/api/posts

###
#Get particular post
GET http://localhost:9080/simple-rpg/api/posts/525d3e7b-bb1f-4c13-bf17-926d1a12e4c0

###
#Get all category posts
GET http://localhost:9080/simple-rpg/api/categories/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76/posts

###
#Create new post
PUT http://localhost:9080/simple-rpg/api/categories/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76/posts/a2883520-bf7b-4ae1-b8a5-5b70a1b90e71
Content-Type: application/json

{
  "content": "Testcontent1",
  "amountOfLikes": 123
}

###
#Get newly created post
GET http://localhost:9080/simple-rpg/api/categories/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76/posts/a2883520-bf7b-4ae1-b8a5-5b70a1b90e71


###
#Patch newly created post
PATCH http://localhost:9080/simple-rpg/api/categories/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76/posts/a2883520-bf7b-4ae1-b8a5-5b70a1b90e71
Content-Type: application/json

{
  "content": "Testcontent1",
  "amountOfLikes": 321
}

###
#Delete newly created post
DELETE http://localhost:9080/simple-rpg/api/categories/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76/posts/a2883520-bf7b-4ae1-b8a5-5b70a1b90e71


###
#Get all categories
GET http://localhost:9080/simple-rpg/api/categories

###
#Get particular category
GET http://localhost:9080/simple-rpg/api/categories/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76

###
#Create new category
PUT http://localhost:9080/simple-rpg/api/categories/f2275513-bf7b-4ae1-b8a5-5b70a1b80e36
Content-Type: application/json

{
  "name": "Category new",
  "positionInHierarchy": 999
}

###
#Get new category
GET http://localhost:9080/simple-rpg/api/categories/f2275513-bf7b-4ae1-b8a5-5b70a1b80e36

###
#Edit new category
PATCH http://localhost:9080/simple-rpg/api/categories/f2275513-bf7b-4ae1-b8a5-5b70a1b80e36
Content-Type: application/json

{
  "name": "Category new",
  "positionInHierarchy": 111
}

###
#Get new category
GET http://localhost:9080/simple-rpg/api/categories/f2275513-bf7b-4ae1-b8a5-5b70a1b80e36

###
#Delete existing category
DELETE http://localhost:9080/simple-rpg/api/categories/5d1da2ae-6a14-4b6d-8b4f-d117867118d4